# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# 初始启动脚本（仅执行一次）
# 用于应用初始壁纸、主题、新设置等
# 建议不要修改或删除此配置及对应的参考文件 ~/.config/hypr/.initial_startup_done
# 只要该参考文件存在，initial-boot.sh 就不会重复执行
exec-once = $HOME/.config/hypr/initial-boot.sh

### 引用外部配置文件 ###
# 定义配置目录路径变量
$configs = $HOME/.config/hypr/configs # 默认配置目录
$UserConfigs = $HOME/.config/hypr/UserConfigs # 用户自定义配置目录

# 预设快捷键配置
source=$configs/Keybinds.conf 

# 启动应用配置（先加载默认，后加载用户自定义）
source= $configs/Startup_Apps.conf 
source= $UserConfigs/Startup_Apps.conf

# 环境变量配置（先加载默认，后加载用户自定义）
source= $configs/ENVariables.conf # 默认环境变量
source= $UserConfigs/ENVariables.conf # 用户环境变量

# 笔记本相关配置（包含用户自定义显示器设置）
source= $configs/Laptops.conf 
source= $UserConfigs/Laptops.conf 
source= $UserConfigs/LaptopDisplay.conf 

# 窗口规则配置（先加载默认，后加载用户自定义）
source= $configs/WindowRules.conf # 默认窗口规则
source= $UserConfigs/WindowRules.conf # 用户窗口规则

# 系统基础设置配置
source= $configs/SystemSettings.conf 

# 用户自定义配置模块
source= $UserConfigs/UserDecorations.conf # 窗口装饰配置
source= $UserConfigs/UserAnimations.conf # 动画效果配置
source= $UserConfigs/UserKeybinds.conf # 用户自定义快捷键
source= $UserConfigs/UserSettings.conf # Hyprland 主要设置
source= $UserConfigs/01-UserDefaults.conf # 默认应用程序设置（优先级最高）

# 显示器管理工具 nwg-displays 的配置文件
source= $HOME/.config/hypr/monitors.conf # 显示器配置
source= $HOME/.config/hypr/workspaces.conf # 工作区配置

source = ./dms/cursor.conf

source = ./dms/outputs.conf
