# 默认显示器配置
# 显示器
monitor=,preferred,auto,1               # 显示器=,首选分辨率,自动位置,缩放倍数1

# 高刷新率
monitor=,highrr,auto,1                  # 显示器=,最高可用刷新率,自动位置,缩放倍数1

# 高分辨率
monitor=,highres,auto,1                 # 显示器=,最高可用分辨率,自动位置,缩放倍数1
