# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171A21)
$foreground = rgb(D2F2FA)
$color0 = rgb(2C2F37)
$color1 = rgb(465879)
$color2 = rgb(8C8694)
$color3 = rgb(8C8694)
$color4 = rgb(8C8694)
$color5 = rgb(5EA3B5)
$color6 = rgb(5EA3B6)
$color7 = rgb(B6E4F0)
$color8 = rgb(7F9FA8)
$color9 = rgb(5D76A2)
$color10 = rgb(BAB2C6)
$color11 = rgb(BAB2C6)
$color12 = rgb(BAB2C6)
$color13 = rgb(7DD9F2)
$color14 = rgb(7ED9F2)
$color15 = rgb(B6E4F0)
