# 这是一个用来放置你自己的默认应用、默认搜索引擎等设置的文件
# 该文件用于设置你自定义的默认应用程序、默认搜索引擎等
# 在此处设置你的默认编辑器，取消注释并重启后生效
# 注意：如果你选择 neovim 或 vim 作为默认编辑器，此行会自动取消注释
env = EDITOR,nvim #default editor
# 定义 KooL 快速设置菜单（快捷键 SUPER SHIFT E）中首选使用的文本编辑器
# 脚本会优先使用上面设置的 EDITOR 变量，若未设置则回退到 nano
$edit=${EDITOR:-nano}
# 下面两个变量用于 UserKeybinds.conf 和 Waybar 模块
$term = alacritty # Terminal （终端）
$files = thunar # File Manager （文件管理器）
# ROFI 搜索（快捷键 SUPER S）使用的默认搜索引擎
$Search_Engine = "https://www.biying.com/search?q={}"
