# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = fcitx5 -d
exec-once = QQ
exec-once = udiskie &
# 自动化系统底层配置：确保默认使用 Index 打开文件夹
exec-once = bash -c 'mkdir -p ~/.config && grep -q "inode/directory=org.kde.index.desktop" ~/.config/mimeapps.list || echo -e "\n[Default Applications]\ninode/directory=org.kde.index.desktop" >> ~/.config/mimeapps.list'
