source = $HOME/.config/hypr/wallust/wallust-hyprland.conf

general {
  border_size = 2          # 窗口边框的厚度（单位：像素）
  gaps_in = 2              # 窗口与窗口之间的间隙大小
  gaps_out = 4             # 窗口与屏幕边缘的间隙大小

  col.active_border = $color12    # 当前活动（焦点）窗口的边框颜色
  col.inactive_border = $color10  # 非活动（失去焦点）窗口的边框颜色
}

decoration {
  rounding = 5            # 窗口圆角的弧度大小

  active_opacity = 1.0     # 当前活动窗口的不透明度（1.0 为完全不透明）
  inactive_opacity = 1     # 非活动窗口的不透明度（你已经改为1，不再变透明）
  fullscreen_opacity = 1.0 # 全屏状态下窗口的不透明度

  dim_inactive = false     # 是否让非活动窗口变暗（你已经改为 false 关闭了）
  dim_strength = 0.1       # 如果开启了变暗，这里控制变暗的程度（0.0 到 1.0，数值越大越暗）
  dim_special = 0.8        # 打开特殊工作区（Special Workspace）时，背后原桌面的变暗程度

  shadow {
    enabled = false         # 是否开启窗口的阴影效果
    range = 3              # 阴影的大小/扩散范围
    render_power = 1       # 阴影的衰减率（1 到 4，数值越大阴影边缘消散得越快）

    color =  $color12      # 活动窗口的阴影颜色
    color_inactive = $color10 # 非活动窗口的阴影颜色
  }

  blur {
    enabled = true         # 是否开启背景模糊效果（只有窗口有透明度时才能看到效果）
    size = 3              # 模糊的半径大小（数值越大，背景越模糊）
    passes = 4             # 模糊的过滤次数（次数越多，模糊越平滑，但更消耗显卡性能）
    new_optimizations = true # 是否开启模糊性能优化（建议保持开启）
    xray = true            # 开启后，浮动窗口后面的模糊不会被底下的窗口影响（提升性能和观感）
    ignore_opacity = true  # 让模糊效果独立计算，不受窗口自身透明度设置的干扰
    special = true         # 是否对特殊工作区（Special Workspace）的背景开启模糊
    popups = true          # 是否对弹出窗口（例如右键菜单、悬浮提示框）开启模糊
  }
}

group {
  col.border_active = $color15 # 窗口被编组（Group）时，当前活动窗口的边框颜色

	groupbar {
		col.active = $color0   # 编组窗口顶部的标题栏/标签条处于活动状态时的颜色
  }
}
