# 开启全局所有窗口默认浮动
windowrule = match:class .*, float on
# 全局默认浮动与尺寸控制块
windowrule {
    name = Global-Float-Rule
    match:class = .*
    float = on
    size = (monitor_w*0.6) (monitor_h*0.6)  # 宽度和高度均设为显示器的 60%
    center = on                             # 强制居中
}
